click/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from click.views import result_view, subject_list_view, subject_view, variant_view, result_list_view, VariantCreateView

app_name = 'click'
urlpatterns = [
    path('subjects/', subject_list_view, name='subject_list'),
    path('subjects/<int:pk>/', subject_view, name='subject'),
    path('variant/<int:pk>/', variant_view, name='variant'),
    path('results/', result_list_view, name='result_list'),
    path('results/<int:pk>/', result_view, name='result'),

    # for teachers
    path('variant/create/', VariantCreateView.as_view(), name='variant_create')
    # path('/<int:pk>')
]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings
from click.views import index_view

urlpatterns = ([
                   path('admin/', admin.site.urls),
               ]
               + i18n_patterns(
            path('i18n/', include('django.conf.urls.i18n')),
            path('', index_view, name='home'),
            path('accaunt/', include('user.urls')),
            path('test/', include('click.urls')),
            prefix_default_language=False
        ))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

# from click.views import   result_view, subject_list_view, subject_view, variant_view
from user.views import RegisterView, ProfileView, EditProfileView, DeleteProfileView, DetailProfileView, logout_view
from django.contrib.auth.views import LoginView, LogoutView
from user.forms import CustomAuthenticationForm

app_name = 'accaunt'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/',
         LoginView.as_view(authentication_form=CustomAuthenticationForm, template_name='pages/login_page.html'),
         name='login'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/detail/<int:pk>/', DetailProfileView.as_view(), name='profile_detail'),
    path('profile/edit/<int:pk>/', EditProfileView.as_view(), name='profile_edit'),
    path('profile/delete/<int:pk>/', DeleteProfileView.as_view(), name='profile_delete'),
    path('logout/', logout_view, name='logout'),
]

templates/pages/delete_profile_page.html
{% extends 'base.html'%}
{% load static %}

{% block title %}
    Delet Page
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <p>{{ object }} - profilingizni rostdan o'chirmoqchimisiz</p>

    </form>
    <input type="submit" value="Tasdiqlash">


{% endblock %}

templates/pages/edit_profile_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Edit page
{% endblock %}

{% block content %}
    <h1>{% blocktranslate %}Profilni o'zgartirish{% endblocktranslate %}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit">{% blocktranslate %}Saqlash{% endblocktranslate %}</button>
    </form>
{% endblock %}

templates/pages/exercise_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Variant: {{ variant.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <h2>{{ variant.title }}</h2>
        <form  method="post">
            {% csrf_token %}
            <ol>
                {% for exercise in exercise_list %}
                    <li>
                        <h6>{{ exercise.text }}</h6>
                        <p>
                            <input class="exercise" type="radio" name="{{exercise.id}}" id="{{exercise.id}}_answer_a" value="answer_a">
                            <label for="{{exercise.id}}_answer_a">{{ exercise.answer_a }}</label>
                        </p>
                        <p>
                            <input class="exercise" type="radio" name="{{exercise.id}}" id="{{exercise.id}}_answer_b" value="answer_b">
                            <label for="{{exercise.id}}_answer_b">{{ exercise.answer_b }}</label>
                        </p>
                        <p>
                            <input class="exercise" type="radio" name="{{exercise.id}}" id="{{exercise.id}}_answer_c" value="answer_c">
                            <label for="{{exercise.id}}_answer_c">{{ exercise.answer_c }}</label>
                        </p>
                        <p>
                            <input class="exercise" type="radio" name="{{exercise.id}}" id="{{exercise.id}}_answer_d" value="answer_d">
                            <label for="{{exercise.id}}_answer_d">{{ exercise.answer_d }}</label>
                        </p>
                    </li>
                {% endfor %}
            </ol>
            <button class="btn btn-outline-dark" type="submit">
                {% blocktranslate %}
                	 Tekshirish
                {% endblocktranslate %}
            </button>
        </form>

    </div>
{% endblock %}

templates/pages/home_page.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}


{% block title %}
    Home page
{% endblock %}


{% block content%}
<div class="only-bg" >
    <h1 class="welcome">
        {% blocktrans %}Welcome to  Home page !{% endblocktrans %}
    </h1>
    <a class="start" href="{% url 'click:subject_list' %}">{% blocktrans %}-->Test yechishni boshlash<--{% endblocktrans %}</a>
</div>
{% endblock%}

templates/pages/login_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% blocktranslate %}Yuborish{% endblocktranslate %}</button>
        </form>
    </div>
{% endblock %}

templates/pages/profile_page.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block title %}
    Profile Page
{% endblock %}

{% block content %}
        <div class="test_decoration">
            <ul class="wrapper">   
                <div class="avatar_wrap">
                     <img class="avatar_img" src="{{ object.avatar.url }}" alt="">
                </div>
                {% for val in object.values %}
                    <li>{{ val }}</li>
                {% endfor %}
                    <div class="ram">
                        <li>
                            {% blocktranslate %}Foydalanuvchi nomi{% endblocktranslate %}:
                            {{ user.username }}
                        </li>
                        <li>
                            {% blocktranslate %}Foydalanuvchi pochtasi{% endblocktranslate %}:
                            {{ user.email }}
                        </li>
                    </div>
                {% if user %}
    
                {% else %}
                    <li>
                        {{ user.first_name }}</li>
                    <li>
                        {{ user.gmail }}</li>
                {% endif %}
            </ul>
            <div class="card_body">
                <a class="linked-1" href="{% url 'accaunt:profile_edit' request.user.pk %}">
                    {% blocktranslate %}Profilni o'zgartirish{% endblocktranslate %}!
                </a>
                <a class="linked-2" href="{% url 'click:result_list' %}">
                    {% blocktranslate %}Natijalarim{% endblocktranslate %}
                </a>
                <a class="linked-3" href="{% url 'accaunt:profile_delete' request.user.pk %}">
                    {% blocktranslate %}Profilni o'chirish{% endblocktranslate %}!
                </a>
            </div>
        </div>

{% endblock %}

templates/pages/register_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Register Page
{% endblock %}

{% block content %}
    <div class="container m-5">
        <form method="post" class="w-50 mx-5">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% blocktranslate %}Saqlash{% endblocktranslate %}</button>
        </form>
    </div>
{% endblock %}

templates/pages/result_list_page.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}


{% block title %}
    Natijalar
{% endblock %}

{% block content %}
    <div class="container">
            {% if result_list %}
    	        <div class="list-group mt-5">
            {% for result in result_list %}
                  <a href="{% url 'click:result' result.id %}" class="list-group-item list-group-item-action" aria-current="true">
                  
                    <div class=" d-flex w-100 justify-content-between">
                        <h5 class="mb-1">
                             {{ result }} 
                        </h5>
                        <small>{{ result.date_completed|date:"d/m/Y H:i:s" }}</small>
                    </div>
                  </a> 

                
            {% endfor %}
        </div>
        {% else %}
    	    {% blocktranslate %}Siz hali variant ishlamadingiz{% endblocktranslate %} !!!
        {% endif %} 
    
    </div>
{% endblock %}

templates/pages/result_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
	RESULT PAGE
{% endblock %}

{% block content %}
    <div class="container">
        <h3>{% blocktranslate %}Natijangiz:{% endblocktranslate %}{{ ball }} / {{ count }}</h3>

        <ol>
            {% for result in object_list %}
                <li>
                    <h6>{{ result.exercise.text }}</h6>
                    <p>
                        A) {{ result.exercise.answer_a }}
                        <span style="color:  {% if result.user_answer == 'answer_a' %} {% if result.exercise.answer == 'answer_a' %} green {% else %} red {% endif %} {% endif %}">
                            {% if result.user_answer == 'answer_a' %}
                                {% if result.exercise.answer == 'answer_a' %}✓    {% else %}⨉
                                {% endif %} {% endif %}
                        </span>
                    </p>
                    <p>
                        B) {{ result.exercise.answer_b }}
                         <span style="color:  {% if result.user_answer == 'answer_b' %} {% if result.exercise.answer == 'answer_b' %} green {% else %} red {% endif %} {% endif %}">
                            {% if result.user_answer == 'answer_b' %}
                                {% if result.exercise.answer == 'answer_b' %}✓    {% else %}⨉
                                {% endif %} {% endif %}
                        </span>
                    </p>
                    <p>
                        C) {{ result.exercise.answer_c }}
                        <span style="color:  {% if result.user_answer == 'answer_c' %} {% if result.exercise.answer == 'answer_c' %} green {% else %} red {% endif %} {% endif %}">
                            {% if result.user_answer == 'answer_c' %}
                                {% if result.exercise.answer == 'answer_c' %}✓  {% else %}✕ 
                                {% endif %} {% endif %}
                        </span>
                    </p>
                    <p>
                        D) {{ result.exercise.answer_d }}
                        <span style="color:  {% if result.user_answer == 'answer_d' %} {% if result.exercise.answer == 'answer_d' %} green {% else %} red {% endif %} {% endif %}">
                            {% if result.user_answer == 'answer_d' %}
                                {% if result.exercise.answer == 'answer_d' %}✓    {% else %}⨉
                                {% endif %} {% endif %}
                        </span>
                    </p>
    
                </li>
            {% endfor %}
        </ol>

    </div>
{% endblock %}

templates/pages/subject_page.html
{% extends 'base.html'%}
{% load i18n %}

{% block title %}
    Test Page
{% endblock %}

{% block content %}
    <div class="container-subject">
        <div>
            <h1>
                {% blocktranslate %}Fanni tanlang{% endblocktranslate %}:
            </h1>
        <div class="list-group">
            {% for subject in subject_list %}
                    <li>
                        <a class="list-group-item list-group-item-action  linked" href="{% url 'click:subject' subject.id %}">{{ subject.name }}</a>
                    </li>
            {% endfor %}
        </div>
                
        </div>
    </div>
{% endblock %}

templates/pages/variant_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
	Variant yaratish
{% endblock %}

{% block content %}
    <div class="container py-5">
        <h1>Variant yaratish:</h1>
        <form method="post">
            {% csrf_token %}
            {% for field in variant_form %}
                <div class="fieldWrapper mt-3">
                    {{ field|add_label_class:"form-label" }}
                    {{ field|add_class:"form-control" }}
                </div>
            {% endfor %}
        
            <hr>

            <div class="row">
                {% for form in formset %}
                    <div class="col-4 shadow p-3 mb-5 bg-body-tertiary rounded">
                        {% for field in form %}
                            {% if field.name not in "id, variant" %}
                                {{ field|add_label_class:"form-label mt-3" }}
                                {{ field|add_class:"form-control"|attr:"rows:3" }}
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>

            <button type="submit" class="btn btn-outline-success mt-4">Saqlash</button>
        </form>
    </div>
{% endblock %}

templates/pages/variant_edit.html
{% extends 'base.html' %}

templates/pages/variant_page.html
{% extends 'base.html'%}
{% load i18n %}

{% block title %}
    VARIANT
{% endblock %}

{% block content%}
    <div class="container-subject">
{#        <h3>#}
{#            {% blocktranslate %}Variantni tanlang{% endblocktranslate %}#}
{#        </h3>#}
        <div class="container">
            <a href="{% url 'click:variant_create' %}?subject={{ subject.id|urlencode }}"
                    class="list-group-item list-group-item-action">Variant yaratish</a>
            <h4>{% blocktranslate %}Variantni tanlang{% endblocktranslate %}:</h4>
        <div class="list-group">
            {% for variant in variant_list %}
                    <a class="list-group-item list-group-item-action linked" href="{% url 'click:variant' variant.id %}">{{ variant.title }}</a>
            {% endfor %}
        </div>
            
        </div>
    </div>
{% endblock %}