click/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from click.views import result_view, subject_list_view, subject_view, variant_view, result_list_view, VariantCreateView

app_name = 'click'
urlpatterns = [
    path('subjects/', subject_list_view, name='subject_list'),
    path('subjects/<int:pk>/', subject_view, name='subject'),
    path('variant/<int:pk>/', variant_view, name='variant'),
    path('results/', result_list_view, name='result_list'),
    path('results/<int:pk>/', result_view, name='result'),

    # for teachers
    path('variant/create/', VariantCreateView.as_view(), name='variant_create')
    # path('/<int:pk>')
]

config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings
from click.views import index_view

urlpatterns = ([
                   path('admin/', admin.site.urls),
               ]
               + i18n_patterns(
            path('i18n/', include('django.conf.urls.i18n')),
            path('', index_view, name='home'),
            path('accaunt/', include('user.urls')),
            path('test/', include('click.urls')),
            prefix_default_language=False
        ))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

# from click.views import   result_view, subject_list_view, subject_view, variant_view
from user.views import RegisterView, ProfileView, EditProfileView, DeleteProfileView, DetailProfileView, logout_view
from django.contrib.auth.views import LoginView, LogoutView
from user.forms import CustomAuthenticationForm

app_name = 'accaunt'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/',
         LoginView.as_view(authentication_form=CustomAuthenticationForm, template_name='pages/login_page.html'),
         name='login'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/detail/<int:pk>/', DetailProfileView.as_view(), name='profile_detail'),
    path('profile/edit/<int:pk>/', EditProfileView.as_view(), name='profile_edit'),
    path('profile/delete/<int:pk>/', DeleteProfileView.as_view(), name='profile_delete'),
    path('logout/', logout_view, name='logout'),
]

templates/components/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">ÚWÙ</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">
                {% blocktrans %} Home {% endblocktrans %}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'click:subject_list' %}">{% blocktrans %} Fanlar {% endblocktrans %}</a>
          </li>
{#          <li class="nav-item dropdown">#}
{#            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">#}
{#              Dropdown#}
{#            </a>#}
{#            <ul class="dropdown-menu">#}
{#              <li><a class="dropdown-item" href="#">Action</a></li>#}
{#              <li><a class="dropdown-item" href="#">Another action</a></li>#}
{#              <li><hr class="dropdown-divider"></li>#}
{#              <li><a class="dropdown-item" href="#">Something else here</a></li>#}
{#            </ul>#}
{#          </li>#}
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true"></a>
          </li>
        </ul> 
        {# ------------------------------------------------------------------------------------------------------------------------------------>    #}
        <div class="d-flex gap-2 d-md-flex justify-content-md-end ms-2">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown">
                            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                                 class="bi bi-person-circle" viewBox="0 0 16 16">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                <path fill-rule="evenodd"
                                d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                            </svg>
                            
                        </a>
                        <ul class="dropdown-menu">
                            {% if request.user.is_authenticated %}
                                <li >
                                    <a class="dropdown-item" href="{% url 'accaunt:profile' request.user.id %}"><i class="bi bi-person about"></i>{% blocktrans %}Profile {% endblocktrans %}</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url "accaunt:logout" %}"><i class="bi bi-box-arrow-left about"></i>Log out</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url "accaunt:login" %}">Sign in</a></li>
                                <li><a class="dropdown-item" href="{% url "accaunt:register" %}">Sign up</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        {#  ----------------------------------------------------------------------------------------------------------------------------------->    #}
      
          <form action="{% url 'set_language' %}" method="post">
              {% csrf_token %}
              <input name="next" type="hidden" value="{{ redirect_to }}">
              <select class="form-select" name="language" onchange="this.form.submit()">
                  {% get_current_language as LANGUAGE_CODE %}
                  {% get_available_languages as LANGUAGES %}
                  {% get_language_info_list for LANGUAGES as language %}
                  {% for language in language %}
                      <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                      	    selected{% endif %}>
                        {{ language.name_local | capfirst }}
                      </option>
                  {% endfor %}

              </select>
          </form>
          
      </div>
    </div>
  </nav>